### ISSUE TITLE
Issue: ATS wont work

### ISSUE THREAD

**Issue by LaocheXe** [sethduda/AdvancedTrainSimulator#11]
Placing tracks down on Tanoa, yet trains wont work.

![wip-tanoatrain](https://user-images.githubusercontent.com/5818022/30189016-50d4f318-93f7-11e7-9a73-261753f210e0.JPG)

Got in the train, but no message pop up saying loading, cant play the horn, nothing...

**Comment by sethduda** [comment]
You need to put track bumpers on each end of the track (and must overlap
the ends of the track). You can join the discord channel (posted on steam
description) if you need more help.
